//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myDataLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class uam2_market1
    {
        public int RecordID { get; set; }
        public string MarketID { get; set; }
        public string CountryCode { get; set; }
        public string RoleName { get; set; }
        public string CompanyType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Location { get; set; }
        public string Location1 { get; set; }
    }
}
