//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myDataLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class userAppAuthority
    {
        public decimal user_app_auth_id { get; set; }
        public string access_org_id { get; set; }
        public string user_id { get; set; }
        public string location_id { get; set; }
        public string application_id { get; set; }
        public string application_role_id { get; set; }
        public string crnt_owsh_typ_ds { get; set; }
        public string default_authoritative_role { get; set; }
        public string record_source { get; set; }
        public string char_attrib_1 { get; set; }
        public string char_attrib_2 { get; set; }
        public string char_attrib_3 { get; set; }
        public string char_attrib_4 { get; set; }
        public string char_attrib_5 { get; set; }
        public string role_prov_by_user_id { get; set; }
        public decimal created_in_trans_batch_id { get; set; }
        public Nullable<decimal> ack_in_eai_batch_id { get; set; }
        public string created_by_user_id { get; set; }
        public System.DateTime creation_date { get; set; }
        public Nullable<decimal> updated_in_trans_batch_id { get; set; }
        public string updated_by_user_id { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<bool> local_account { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<bool> BoolFlag { get; set; }
        public string char_attrib_6 { get; set; }
        public string char_attrib_7 { get; set; }
        public string char_attrib_8 { get; set; }
        public string char_attrib_9 { get; set; }
        public string char_attrib_10 { get; set; }
        public string char_attrib_11 { get; set; }
        public string char_attrib_12 { get; set; }
        public string char_attrib_13 { get; set; }
        public string char_attrib_14 { get; set; }
        public string char_attrib_15 { get; set; }
        public string char_attrib_16 { get; set; }
        public string char_attrib_17 { get; set; }
        public string char_attrib_18 { get; set; }
        public string char_attrib_19 { get; set; }
        public string char_attrib_20 { get; set; }
        public Nullable<bool> IsOverrideAccess { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
    }
}
